### ISSUE TITLE
TypeError when I use plugins manager

### ISSUE THREAD

**Issue by cyf203** [Image-Py/cellpose-plgs#2]
When I try to explore the plugin using plugin manager. The manager window looks strange and I saw a error message:  
![image](https://user-images.githubusercontent.com/26474966/74292192-6e5d3980-4d05-11ea-8b21-0c535f60ce96.png)

![image](https://user-images.githubusercontent.com/26474966/74291992-c6477080-4d04-11ea-960c-e86a549c6525.png)

**Comment by cyf203** [comment]
I noticed that I have a module error prior to this TypeError. So, I reinstalled NumPy and now the module error is gone. But the TypeError still there and I cannot use the plugins manager.

**Comment by cyf203** [comment]
Nevermind. I think this issue fixed by update the imagepy

**Comment by yxdragon** [comment]
imagepy is just a ui framework based on your local python environment, and when you install a plugin, imagepy use 'pip install xxx' to solve the dependance, So makesure 'pip install' works, then imagepy would works.
