### ISSUE TITLE
Batch process with script version using cellpose plgs

### ISSUE THREAD

**Issue by cyf203** [Image-Py/cellpose-plgs#4]
Dear ImagePy team,

I knew ImagePy has a very user-friendly UI. But, given the cellulose computation is time-consuming. Often time, we have to wait for 5-10 minutes to process one image. So, I think the batch process many images overnight will be very helpful. If we had a working pipeline, e.g., cellpose segmentation --> imagery geometry analysis --> export the coordinate of the mask for each channel into either Pandas or Numpy, I wonder how to use the script to do it? or is there anything that ImagePy can handle in the UI? We are really looking forward to seeing a way to achieve this.

Thank you,

**Comment by yxdragon** [comment]
imagepy supports image sequence. you can use File > Import > Sequence to import all image. (must be in the same format and same size), then all the operation would be in batch mode. cell pose would output a mask sequence, and geometry analysis would output a dataframe with a column named "slice id". and we can also use Window > Develop Sute Tools to record a macros. we can even record "segment, save the mask to disk as png, analysis, save the result to csv" all. then you can process overnight, you would got all the result.

about imagepy's usage, please post a thread in [image.sc](image.sc). there I can paste the step with picture in detail, even give you a macros. I think github is not a place to talk about "how to use".

**Comment by cyf203** [comment]
Thank you!
